swagger: "2.0"
info:
  title: Sunglasses API
  description: An API to support the sunglasses platform
  version: 1.0.0
schemes:
  - https
basePath: /
produces:
  - application/json
paths:
  /brands:
    get:
      summary: Brands
      description: The Brands endpoint allows user to see all brands
      tags:
        - Brands
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Brand'
      default:
          description: Unexpected Error
          schema:
            type: string
  /brands/{brandId}/products:
    get:
      summary: Products by Brand Id
      description: This endpoint allows users to select brand and see all products associated with that brand
      tags:
        - Brands
      parameters:
        - name: brandId
          in: path
          description: The id of the brand to see products
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Brand'
        '404':
          description: 'No products with that brand Id found.'
          schema:
            type: string
  /products:
    get:
      summary: Product Search
      description: The product endpoints allows user to search for individual product
      tags:
        - Product Search
      parameters:
        - name: productName
          in: query
          description: The name of the product the user is searching for
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Product'
        '404':
          description: 'Please enter the name of the product you are searching for.'
          schema:
            type: string
        '404':
          description: 'The product does not exist'
          schema:
            type: string
          
 